const HOME_BASE_ROUTE = '/';

const DASHBOARD_BASE_ROUTE = '/dashboard';

const GPU_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/gpu`;

const USERS_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/users`;

const FINANCE_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/finance`;

const SUPPORT_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/support`;

const MESSAGES_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/messages`;

const MARKETING_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/marketing`;

const AI_SERVICES_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/ai-services`;

const API_PLATFORM_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/api-platform`;

const NEWS_BASE_ROUTE = `${DASHBOARD_BASE_ROUTE}/news`;

export {
  GPU_BASE_ROUTE,
  HOME_BASE_ROUTE,
  USERS_BASE_ROUTE,
  SUPPORT_BASE_ROUTE,
  FINANCE_BASE_ROUTE,
  MESSAGES_BASE_ROUTE,
  MARKETING_BASE_ROUTE,
  DASHBOARD_BASE_ROUTE,
  AI_SERVICES_BASE_ROUTE,
  API_PLATFORM_BASE_ROUTE,
  NEWS_BASE_ROUTE,
};
