import {
  AI_SERVICES_ROUTES,
  API_PLATFORM_ROUTES,
  FINANCE_ROUTES,
  GPU_ROUTES,
  HOME_ROUTES,
  MARKETING_ROUTES,
  MESSAGES_ROUTES,
  SUPPORT_ROUTES,
  USERS_ROUTES,
} from './routes';

const routeNames: { [x: string]: string } = {
  [HOME_ROUTES.DASHBOARD]: 'داشبورد',
  [HOME_ROUTES.HOME]: 'خانه',
  [HOME_ROUTES.LOGIN]: 'ورود',
  [AI_SERVICES_ROUTES.API_PARK]: 'API پارک',
  [AI_SERVICES_ROUTES.CATEGORIES]: 'کتگوری',
  [AI_SERVICES_ROUTES.COLLECTION]: 'کالکشن',
  [AI_SERVICES_ROUTES.LOGS]: 'گزارش‌ها',
  [AI_SERVICES_ROUTES.SERVERS]: 'سرورها',
  [API_PLATFORM_ROUTES.APIS]: 'APIها',
  [API_PLATFORM_ROUTES.LOGS]: 'گزارش‌ها',
  [API_PLATFORM_ROUTES.SERVERS]: 'سرورها',
  [FINANCE_ROUTES.ADD_FACTORS]: '',
  // [FINANCE_ROUTES.BANKS]: 'لیست بانک‌ها',
  [FINANCE_ROUTES.FACTORS]: 'فاکتورها',
  [FINANCE_ROUTES.GIFT_CODE]: 'کد هدیه',
  // [FINANCE_ROUTES.INVITATION_CODE]: 'کد دعوت',
  [FINANCE_ROUTES.TRANSACTIONS]: 'تراکنش‌ها',
  [GPU_ROUTES.CATEGORIES]: '',
  [GPU_ROUTES.COLLECTION]: '',
  [GPU_ROUTES.CONFIGURATION]: 'پیکربندی‌ها',
  [GPU_ROUTES.DISKS]: 'دیسک‌ها',
  [GPU_ROUTES.GPUS]: 'GPUها',
  [GPU_ROUTES.LOGS]: 'گزارش‌ها',
  [GPU_ROUTES.MOTHERBOARDS]: 'مادربرد‌ها',
  [GPU_ROUTES.SERVERS]: 'سرورها',
  [GPU_ROUTES.RESOURCE]: 'دسته‌بندی منابع',
  [MARKETING_ROUTES.CAMPAIGN]: 'کمپین‌ها',
  [MESSAGES_ROUTES.EMAIL]: 'ایمیل',
  [MESSAGES_ROUTES.NOTIFICAITONS]: 'اعلان',
  [MESSAGES_ROUTES.SMS]: 'پیامک',
  [MESSAGES_ROUTES.PUBLIC_MESSAGE]: 'پیام‌های همگانی',
  [MESSAGES_ROUTES.DEFAULT_MESSAGE]: 'پیام پیشفرض',
  [SUPPORT_ROUTES.ADD_TICKET]: 'افزودن تیکت',
  [SUPPORT_ROUTES.FAQ]: 'سؤالات متداول',
  [SUPPORT_ROUTES.TERMS_AND_POLICIES]: 'قوانین و شرایط استفاده',
  [SUPPORT_ROUTES.TICKETING]: 'تیکت‌ها',
  [USERS_ROUTES.ADD_USER]: 'افزودن کاربر',
  [USERS_ROUTES.LIST]: 'لیست کاربران',
  [USERS_ROUTES.TOKENS]: 'توکن‌ها',
};

export { routeNames };
