import {
  DASHBOARD_BASE_ROUTE,
  HOME_BASE_ROUTE,
  AI_SERVICES_BASE_ROUTE,
  API_PLATFORM_BASE_ROUTE,
  FINANCE_BASE_ROUTE,
  GPU_BASE_ROUTE,
  MARKETING_BASE_ROUTE,
  MESSAGES_BASE_ROUTE,
  SUPPORT_BASE_ROUTE,
  USERS_BASE_ROUTE,
  NEWS_BASE_ROUTE,
} from './baseRoutes';

const HOME_ROUTES = {
  HOME: HOME_BASE_ROUTE,
  DASHBOARD: DASHBOARD_BASE_ROUTE,
  LOGIN: `${HOME_BASE_ROUTE}/login`,
};

const AI_SERVICES_ROUTES = {
  LOGS: `${AI_SERVICES_BASE_ROUTE}/logs`,
  SERVERS: `${AI_SERVICES_BASE_ROUTE}/servers`,
  API_PARK: `${AI_SERVICES_BASE_ROUTE}/api-park`,
  CATEGORIES: `${AI_SERVICES_BASE_ROUTE}/categories`,
  COLLECTION: `${AI_SERVICES_BASE_ROUTE}/collection`,
  ADD_COLLECTION: `${AI_SERVICES_BASE_ROUTE}/collection/add`,
  EDIT_COLLECTION: `${AI_SERVICES_BASE_ROUTE}/collection/edit`,
};

const API_PLATFORM_ROUTES = {
  APIS: `${API_PLATFORM_BASE_ROUTE}/apis`,
  LOGS: `${API_PLATFORM_BASE_ROUTE}/logs`,
  SERVERS: `${API_PLATFORM_BASE_ROUTE}/servers`,
};

const FINANCE_ROUTES = {
  FACTORS: `${FINANCE_BASE_ROUTE}/factors`,
  ADD_FACTORS: `${FINANCE_BASE_ROUTE}/factors/add`,
  EDIT_FACTOR: `${FINANCE_BASE_ROUTE}/factors/edit`,
  GIFT_CODE: `${FINANCE_BASE_ROUTE}/gift-code`,
  ADD_GIFT_CODE: `${FINANCE_BASE_ROUTE}/gift-code/add`,
  EDIT_GIFT_CODE: `${FINANCE_BASE_ROUTE}/gift-code/edit`,
  TRANSACTIONS: `${FINANCE_BASE_ROUTE}/transactions`,
  ADD_TRANSACTIONS: `${FINANCE_BASE_ROUTE}/transactions/add`,
};

const GPU_ROUTES = {
  CATEGORIES: `${GPU_BASE_ROUTE}/categories`,
  COLLECTION: `${GPU_BASE_ROUTE}/collection`,
  CONFIGURATION: `${GPU_BASE_ROUTE}/configuration`,
  DISKS: `${GPU_BASE_ROUTE}/disks`,
  GPUS: `${GPU_BASE_ROUTE}/gpus`,
  LOGS: `${GPU_BASE_ROUTE}/logs`,
  MOTHERBOARDS: `${GPU_BASE_ROUTE}/motherboards`,
  SERVERS: `${GPU_BASE_ROUTE}/servers`,
  RESOURCE: `${GPU_BASE_ROUTE}/resource`,
};

const MARKETING_ROUTES = {
  CAMPAIGN: `${MARKETING_BASE_ROUTE}/campaign`,
};

const MESSAGES_ROUTES = {
  EMAIL: `${MESSAGES_BASE_ROUTE}/?tab=emails`,
  ADD_EMAIL_MESSAGE: `${MESSAGES_BASE_ROUTE}/add-email`,
  NOTIFICAITONS: `${MESSAGES_BASE_ROUTE}/?tab=notifications`,
  ADD_NOTIFICATION_MESSAGE: `${MESSAGES_BASE_ROUTE}/add-notif`,
  SMS: `${MESSAGES_BASE_ROUTE}/?tab=sms`,
  ADD_SMS: `${MESSAGES_BASE_ROUTE}/add-sms`,
  PUBLIC_MESSAGE: `${MESSAGES_BASE_ROUTE}/?tab=public-message`,
  ADD_PUBLIC_MESSAGE: `${MESSAGES_BASE_ROUTE}/add-public-message`,
  ADD_SMS_MESSAGE: `${MESSAGES_BASE_ROUTE}/add-sms`,
  DEFAULT_MESSAGE: `${MESSAGES_BASE_ROUTE}/default-message`,
};

const SUPPORT_ROUTES = {
  FAQ: `${SUPPORT_BASE_ROUTE}/faq`,
  TERMS_AND_POLICIES: `${SUPPORT_BASE_ROUTE}/terms-and-policies`,
  TICKETING: `${SUPPORT_BASE_ROUTE}/ticketing?tab=ticket-list`,
  CATEGORY: `${SUPPORT_BASE_ROUTE}/ticketing?tab=category-questions`,
  ADD_CATEGORY: `${SUPPORT_BASE_ROUTE}/category`,
  ADD_TICKET: `${SUPPORT_BASE_ROUTE}/ticketing/add-ticket`,
};

const USERS_ROUTES = {
  LIST: `${USERS_BASE_ROUTE}/list`,
  ADD_USER: `${USERS_BASE_ROUTE}/add-user`,
  TOKENS: `${USERS_BASE_ROUTE}/tokens`,
};

const NEWS_ROUTES = {
  LIST: `${NEWS_BASE_ROUTE}`,
  ADD: `${NEWS_BASE_ROUTE}/add`,
  EDIT: `${NEWS_BASE_ROUTE}/edit`,
};

export {
  AI_SERVICES_ROUTES,
  API_PLATFORM_ROUTES,
  DASHBOARD_BASE_ROUTE,
  FINANCE_ROUTES,
  GPU_ROUTES,
  HOME_ROUTES,
  MARKETING_ROUTES,
  MESSAGES_ROUTES,
  SUPPORT_ROUTES,
  USERS_ROUTES,
  NEWS_ROUTES,
};
