const strings = {
  cancel: 'انصراف',
  approve: 'تایید',
  description: 'توضیحات',
  titleIsRequired: 'عنوان اجباری‌ است',
  descriptionIsRequired: 'توضیحات اجباری‌ است',
  areYouSure: 'آیا مطمئن هستید؟',
  deprecateHintMessage:
    'پس از منقضی شدن، دیگر امکان استفاده از این نسخه برای کاربران وجود ندارد.',
  deprecateAPI: 'منقضی کردن API',
  willShowInApiMarkert: 'با تأیید کردن، API در مارکت منتشر خواهد شد.',
  rejectAPI: 'مردود کردن API',
  approveApi: 'تایید کردن API',
  reportResloveError: 'گزارش رفع مشکل',
  rejectTitle: 'عنوان پیام به ارائه دهنده',
  additionalDescription: 'توضیحات بیشتر را وارد کنید.',
  apisList: 'لیست APIها',
  reports: 'گزارش‌ها',
  waitingForAccept: 'در انتظار تایید',
  deprecating: 'درحال منقضی شدن',
  deprecated: 'منقضی شده',
  approved: 'تایید شده',
  incomplete: 'ناقص',
  rejected: 'مردود',
  serviceError: 'خطای سرویس',
  apiName: 'نام API',
  provider: 'ارائه دهنده',
  version: 'ورژن',
  usersCount: 'تعداد کاربران',
  requestsCount: 'تعداد فراخوانی',
  totalRequestsCount: 'مجموع فراخوانی‌ها',
  status: 'وضعیت',
  tableActions: 'عملیات',
  approvedDate: 'تاریخ کسب تأییدیه',
  userName: 'نام کاربر',
  resolveApiError:
    'با زدن دکمه «تأیید»، به تمامی استفاده کنندگان سرویس شما، رفع مشکل سرویس اطلاع داده خواهد شد.',
  apiCount: 'تعداد APIها',
  earningProfit: 'اعتبار کسب شده (تومان)',
  avrageLatencyMs: 'میانگین تأخیر(ms)',
  avrageSatisfaction: 'میانگین رضایت کاربران',
  registerDate: 'زمان ثبت نام',
  notAnsweredTicket: 'تیکت در انتظار پاسخ',
  view: 'مشاهده',
  inGpuQueue: 'کاربر در صف رایانش گرافیکی',
  inApiQueue: 'کاربر در صف استفاده از API',
  week: 'هفته',
  weekly: 'هفتگی',
  month: 'ماه',
  monthly: 'ماهانه',
  year: 'سال',
  yearly: 'سالانه',
  newUsers: 'کاربران جدید',
  increase: 'رشد',
  decrease: 'کاهش',
  production: 'پروداکشن',
  zanjan: 'زنجان',
  activeUsers: 'کاربران فعال',
  totalUsers: 'کل کاربران',
  gpuComputing: 'رایانش گرافیکی',
  platform: 'پلتفرم',
  apiMarket: 'API مارکت',
  common: 'مشترک',
  user: 'کاربر',
  compareToLastMonth: 'نسبت به ماه گذشته',
  gpuComputingUsers: 'کاربران رایانش گرافیکی',
  platformUsers: 'کاربران پلتفرم',
  apiMarketUsers: 'کاربران API مارکت',
  commonUsers: 'کاربران مشترک',
  remainCharge: 'باقی مانده شارژ',
  usedApi: 'استفاده از api',
  withDrawCharge: 'برداشت شده',
  incomes: 'دریافتی‌ها',
  totalIncome: 'مجموع دریافتی‌ها از ابتدا',
  toman: 'تومان',
  remainingUserCharges: 'باقیمانده شارژ حساب کاربران',
  providersWithDraw: 'سهم برداشت شده از ارائه‌دهندگان',
  apiPlatform: 'پلتفرم ارائه API',
  totalVersions: 'کل ورژن‌ها از ابتدا',
  inQueueUsers: 'کاربران در صف',
  usersCurrentlyUsing: 'کاربران درحال استفاده',
  totalApis: 'کل APIها',
  mostUsedApis: 'APIهای پرتقاضا',
  mostSellerApis: 'APIهای پردرآمد',
  usersCurrentlyComputing: 'کاربران درحال پردازش',
  avarageUseHours: 'میانگین زمان استفاده (ساعت)',
  mostUseGpu: 'GPUهای پرتقاضا',
  tickets: 'تیکت‌ها',
  ticket: 'تیکت‌',
  addNewFactor: 'افزودن فاکتور جدید',
  price: 'مبلغ',
  priceToToman: 'مبلغ به تومان',
  discount: 'تخفیف',
  percentageDiscount: 'تخفیف به درصد',
  department: 'دپارتمان',
  createdDate: 'تاریخ ایجاد',
  dueDate: 'تاریخ سررسید',
  submit: 'ثبت',
  cancelAction: 'لغو عملیات',
  deleteModalTitle: 'آیا مطمئن هستید؟',
  deleteModalDecription:
    'با حذف این مورد، امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  deleteModalText: 'با پاک کردن این مورد،  تمامی اطلاعات آن از بین خواهد رفت.',
  deleteButtonText: 'حذف کردن',
  factors: 'فاکتورها',
  done: 'پرداخت شده',
  expired: 'منقضی',
  fail: 'پرداخت ناموفق',
  inPorgress: 'در انتظار پرداخت',
  num: 'شماره',
  discountColumn: 'تخفیف(٪)',
  priceColumn: 'مبلغ(تومان)',
  giftCode: 'کد هدیه',
  amountValue: 'مقدار اعتبار',
  tomanAmountValue: 'مقدار اعتبار به تومان',
  expiredDate: 'تاریخ انقضاء',
  totalCapacity: 'تعداد کل ظرفیت',
  usedCapacity: 'تعداد استفاده شده',
  remainingCapacity: 'ظرفیت باقی‌مانده',
  loginToYourAccount: 'ورود به حساب کاربری',
  phoneOrEmail: 'شماره موبایل/ایمیل*',
  password: 'کلمه عبور',
  login: 'ورود',
  forgetPassword: 'فراموشی کلمه عبور',
  emails: 'ایمیل‌ها',
  sms: 'پیامک‌ها',
  notifications: 'اعلان‌ها',
  public_messages: 'پیام‌های همگانی',
  add_new_public_message: 'افزودن پیام همگانی جدید',
  edit_new_public_message: 'ویرایش پیام همگانی',
  add_new_default_message: 'افزودن متن پیش فرض جدید',
  edit_new_default_message: 'ویرایش متن پیش فرض',
  add_new_email_message: 'افزودن ایمیل جدید',
  edit_email_message: 'ویرایش ایمیل',
  add_new_sms_message: 'افزودن پیامک جدید',
  edit_new_sms: 'ویرایش پیامک',
  add_new_notif_message: 'افزودن اعلان جدید',
  edit_notif_message: 'ویرایش اعلان',
  default_message: 'متن پیش فرض',
  all: 'همه',
  general: 'عمومی',
  accounting: 'مالی',
  advertising: 'تبلیغاتی',
  invite: 'دعوت نامه',
  recivers: 'دریافت کنندگان *',
  selectRecivers: 'انتخاب دریافت کننده',
  messageSubject: 'موضوع پیام *',
  categoryName: 'نام دسته‌بندی*',
  addCategory: 'افزودن دسته‌بندی جدید',
  editCategory: 'ویرایش دسته‌بندی',
  notifMessageSubject: 'نام اعلان گروهی',
  emailSubject: 'موضوع ایمیل (Subject)*',
  notifSubject: 'موضوع اعلان*',
  smsGroupName: 'نام پیامک گروهی',
  notifGroupName: 'نام اعلان گروهی',
  generalMessage: 'پیام گروهی',
  smsMessageName: 'نام پیامک گروهی',
  generalMessageText: 'نام پیام گروهی',
  notifMessageName: 'موضوع اعلان*',
  emailGroupName: 'نام ایمیل گروهی',
  sendDateTo: 'تاریخ ارسال تا *',
  sendDateFrom: 'تاریخ ارسال از *',
  sendDate: 'تاریخ ارسال*',
  sendTimeTo: 'ساعت ارسال تا',
  sendTimeFrom: 'ساعت ارسال از',
  sendTime: 'ساعت ارسال ',
  category: 'دسته‌بندی',
  selectCategory: 'انتخاب دسته‌بندی',
  assign_ticket: 'تخصیص تیکت',
  choose_operator: 'انتخاب اپراتور',
  cancel_operation: 'لغو عملیات',
  versionFa: 'نسخه',
  choose_version: 'انتخاب نسخه',
  add_user: 'اضافه کردن کاربر',
  choose_user: 'انتخاب کاربر*',
  choose_category: 'انتخاب دسته‌بندی',
  priority: 'اولویت',
  choose_priority: 'انتخاب اولویت',
  subject: 'عنوان درخواست',
  input_text: 'متن ورودی',
  add_new_ticket: 'افزودن تیکت جدید',
  close_ticket: 'بستن تیکت',
  close_ticket_description: 'با بستن تیکت، امکان گفتگو از بین خواهد رفت.',
  close_ticket_title: 'آیا مطمئن هستید؟',
  loadingFaq: 'در حال بارگذاری سؤالات متداول...',
  updating: 'در حال بروزرسانی...',
  showing: 'در حال نمایش',
  scheduledToSend: 'برنامه‌ریزی شده جهت ارسال',
  sent: 'ارسال شده',
  unsuccessful: 'ناموفق',
  destination: 'مقصد',
  sendTimeRange: 'بازه ارسال',
  messageText: 'متن پیام',
  generalMessages: 'پیام‌های همگانی',
  emailMessages: 'لیست ایمیل‌ها',
  smsMessages: 'لیست پیامک‌ها',
  notifMessages: 'لیست اعلان‌ها',
  answerQuestions: 'به موارد زیر پاسخ دهید',
  low: 'کم',
  up: 'بالا',
  down: 'پایین',
  high: 'زیاد',
  medium: 'متوسط',
  users: 'کاربران',
  addUser: 'افزودن کاربر جدید',
  email: 'ایمیل*',
  accessLevel: 'سطح دسترسی',
  assignToMe: 'تخصیص به خود',
  assignToOthers: 'تخصیص به دیگران',
  opened: 'باز',
  user_answer: 'در انتظار پاسخ کاربر',
  admin_answer: 'در انتظار پاسخ شما',
  closed: 'بسته',
  requestId: 'شماره درخواست',
  operator: 'اپراتور',
  planType: 'نوع پلن',
  request: 'فراخوانی',
  activatedDate: 'تاریخ فعال‌سازی',
  activatedTime: 'زمان فعال‌سازی',
  maxDailyRequest: 'فراخوانی روزانه (بیشینه)',
  maxMonthlyRequest: 'فراخوانی ماهانه (بیشینه)',
  remainingTime: 'زمان باقی‌مانده',
  day: 'روز',
  remainingMonthlyRequest: 'تعداد فراخوانی ماهانه باقی‌مانده',
  remainingDailyRequest: 'تعداد فراخوانی روزانه باقی‌مانده',
  packageExpireDate: 'تاریخ اتمام بسته',
  totalRequestCall: 'تعداد فراخوانی انجام شده',
  totalComputingTime: 'زمان پردازش شده',
  freeUseTime: 'زمان استفاده رایگان',
  hour: 'ساعت',
  to: 'تا',
  useCapacity: 'حجم مصرف شده',
  providerProfit: 'سهم ارائه‌ دهنده',
  platformProfit: 'سهم پلتفرم',
  changeProviderProfit: 'تغییر سهم ارائه‌ دهنده',
  ignore: 'لغو',
  admin: 'ادمین',
  changeAccessLevel: 'تغییر سطح دسترسی',
  active: 'فعال',
  deactive: 'غیرفعال',
  userStatus: 'وضعیت کاربر',
  changeUserStatus: 'تغییر وضعیت کاربر',
  userInfo: 'مشخصات کاربری',
  apiPackages: 'بسته‌های API',
  gpuPackages: 'بسته‌های GPU',
  myApi: 'APIهای ارائه شده',
  finance: 'امور مالی',
  setting: 'تنظیمات',
  token: 'توکن',
  nickName: 'نام مستعار',
  registerationDate: 'تاریخ عضویت',
  lastLogin: 'آخرین دسترسی',
  access: 'دسترسی',
  domain: 'سامانه',
  earned: 'اعتبار کسب شده',
  withdraw_amount: 'اعتبار قابل برداشت',
  remain_charge: 'اعتبار باقی مانده',
  submit_transaction: 'ثبت تراکنش',
  transaction_status: 'وضعیت تراکنش:',
  transaction_kind: 'نوع تراکنش:',
  transaction_id: 'شماره تراکنش',
  editTransaction: 'ویرایش تراکنش',
  deposit: 'واریز',
  withdraw: 'برداشت',
  canceled: 'لغو شده',
  inprogress: 'در حال اقدام',
  successful: 'موفق',
  TomanPrice: 'مبلغ (تومان)',
  date: 'زمان',
  title: 'عنوان',
  transactionType: 'نوع تراکنش',
  depositCharge: 'افزایش اعتبار',
  withdrawCharge: 'برداشت اعتبار',
  factor: 'فاکتور',
  package: 'پکیج',
  wage: 'دستمزد',
  buyApi: 'خرید API',
  saleApi: 'فروش API',
  compute: 'محاسبه',
  deactivedPhoneNumber: 'شماره موبایل کاربر فعال نشده است.',
  notRegisteredPhoneNumber: 'شماره موبایل کاربر ثبت نشده است.',
  resendActivationEmail: 'ارسال مجدد ایمیل فعالسازی',
  deacitvedEmail: 'ایمیل کاربر فعال نشده است.',
  has: 'دارد',
  doestNotHave: 'ندارد',
  apiPackage: 'بسته API',
  gpuPackage: 'بسته GPU',
  registeredApi: 'API ثبت شده',
  notRegistered: 'ثبت نشده',
  editUserAccountInfo: 'ویرایش اطلاعات حساب کاربری',
  sumbitChanges: 'ثبت تغییرات',
  editInfo: 'ویرایش مشخصات',
  firstName: 'نام',
  lastName: 'نام خانوادگی',
  phoneNumber: 'شماره موبایل',
  gender: 'جنسیت',
  newsSummary: 'خلاصه خبر',
  edit: 'ویرایش',
  addNewsTitle: 'افزودن خبر جدید',
  editNews: 'ویرایش خبر',
  news: 'اخبار',
  publishDate: 'تاریخ انتشار',
  tags: 'تگ‌ها',
  thumbnail: 'تصویر شاخص (thumbnail)',
  addressSuffix: 'پسوند آدرس (slug)',
  newsContent: 'شرح اخبار',
  selectOption: 'انتخاب کنید',
  gpus: 'GPUها',
  model: 'مدل',
  ram: 'رم',
  brand: 'برند',
  codaCore: 'تعداد هسته Cuda',
  freeHours: 'ساعت استفاده رایگان',
  freeDays: 'بازه استفاده رایگان (روز)',
  motherboards: 'مادربردها',
  cores: 'تعداد هسته',
  motherboard: 'مادربرد',
  hourlyPrice: 'قیمت استفاده ساعتی (تومان) ',
  name: 'نام',
  capacity: 'حجم(GB)',
  configuration: 'پیکربندی',
  duplicateConfiguration: 'ایجاد پیکربندی مشابه',
  deleteConfiguration:
    'با پاک کردن این مورد تمامی اطلاعات آن‌ از بین خواهد رفت.',
  remove: 'پاک کردن ',
  chooseBrand: 'برند را انتخاب کنید',
  discountPercent: 'درصد تخفیف',
  usage: 'میزان استفاده',
  logs: 'گزارش‌ها',
  packageStatus: 'وضعیت بسته',
  packageName: 'نام بسته',
  processor: 'پردازنده',
  startTime: 'زمان شروع',
  finishReserve: 'زمان اتمام رزرو',
  server: 'سرور',
  servers: 'سرورها',
  errors: 'مشکلات',
  downServer: 'پایین آوردن سرور',
  seeLogs: 'مشاهده لاگ',
  downSeverDescription:
    'با پایین آوردن سرور، دسترسی نام کاربر به سرور پردازشی از بین خواهد رفت.',
  createDate: 'زمان ایجاد',
  errorMessage: 'متن خطا',
  modelName: 'نام مدل',
  totalCount: 'تعداد کل',
  freeCount: 'تعداد آزاد',
  modelInfo: 'اطلاعات مدل',
  models: 'مدل‌ها',
  podName: 'نام pod',
  nodeName: 'نام node',
  nodes: 'nodها',
  editFactor: 'ویرایش فاکتور',
  submitChanges: 'ثبت تغییرات',
  addNewGiftCode: 'افزودن کد هدیه جدید',
  codeTitle: 'عنوان کد',
  editGiftCode: 'ویرایش کد هدیه',
  deleteModalDescription:
    'با حذف کد هدیه، امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  delete: 'حذف کردن',
  transactions: 'تراکنش‌ها',
  actions: 'عملیات',
  createNewTransaction: 'ایجاد تراکنش جدید',
  amount: 'مبلغ',
  amountToToman: 'مبلغ به تومان',
  creditDeposit: 'افزایش اعتبار',
  creditWithdraw: 'برداشت اعتبار',
  buyAPI: 'خرید API',
  saleAPI: 'فروش API',
  inProgress: 'در حال اقدام',
  failed: 'ناموفق',
  time: 'زمان',
  tomanAmount: 'مبلغ(تومان)',
  submitTransaction: 'ثبت تراکنش',
  failedTransaction: 'تراکنش ناموفق',
  successfulTransaction: 'تراکنش موفق',
  transactionNum: 'شماره تراکنش',
  confirm: 'تأیید',
  placeholderText: 'متن راهنما پیش‌فرض',
  transactionStatus: 'وضعیت تراکنش',
  inAwaitAction: 'در انتظار اقدام',
  error: 'خطا',
  running: 'درحال اجرا',
  turnedOff: 'خاموش شده',
  pending: 'در انتظار آماده سازی',
  prepare: 'درحال آماده‌سازی',
  shutDownByAssign: 'خاموش شده بدلیل اساین شدن',
  shutDownByAdmin: 'خاموش شده توسط ادمین',
  yes: 'بله',
  no: 'خیر',
  startServerMSG: 'از روشن کردن سرور مطمئن هستید؟',
  shutdownServerMSG:
    'با خاموش کردن سرور امکان دسترسی به این سرور از بین خواهد رفت.',
  deployServer: 'بالا آوردن سرور',
  shutdownServer: 'پایین آوردن سرور',
  useGpu: 'استفاده از GPU',
  cpuUsage: 'cpu درخواستی (core)',
  ramUsage: 'ram درخواستی (GB)',
  urlPath: 'مسیر حافظه',
  pathName: 'اسم حافظه',
  subjectTitle: 'عنوان پیام را وارد کنید',
  subjectDescription: 'متن پیام را وارد کنید',
  createDefaultMessage: 'ایجاد متن پیشفرض',
  anyDefaultMessage: 'تاکنون متن پیش فرضی ثبت نشده است.',
  send: 'ارسال',
  optionalDescription: 'توضیحات (اختیاری)',
  sendFile: 'ارسال فایل',
  fileLimitation: 'حجم فایل نباید بیشتر از 10 مگابایت باشد!',
  allowedFileType: 'فقط فایل‌های PDF و تصویر (JPEG, PNG) مجاز هستند!',
  yourMessage: 'پیام خود را بنویسید...',
  closedByAdmin: 'تیکت توسط ادمین بسته شد.',
  pdfFile: 'PDF فایل',
  editTicketCategory: 'ویرایش دسته‌بندی تیکت',
  closing: 'در حال بستن...',
  sending: 'در حال ارسال...',
  assignedToMe: 'اختصاص داده شده به من',
  openTicket: 'تیکت‌های باز',
  attachedFile: 'فایل پیوست',
  createdBy: 'ایجاد شده توسط ',
  chatStart: 'برای شروع گفتگو، تیکتی را از لیست انتخاب کنید',
  ticketStatus: ' تیکت مورد نظر وجود ندارد یا حذف شده است',
  messageDeled: 'پیام با موفقیت حذف شد',
  collections: 'مجموعه‌ها',
  collectionName: 'نام مجموعه',
  lastEdit: 'آخرین ویرایش',
  showOrder: 'ترتیب نمایش',
  collectionInfo: 'اطلاعات مجموعه',
  seoInfo: 'اطلاعات سئو',
  collectionEnglishName: 'نام لاتین مجموعه',
  addNewCollection: 'افزودن مجموعه جدید',
  editCollection: 'ویرایش مجموعه ',
  submitCollectionInfo: 'ثبت اطلاعات مجموعه',
  collectionLatinName: 'نام لاتین مجموعه',
  sortBasedOn: 'مرتب‌سازی بر اساس',
  select: 'انتخاب کنید',
  rankForShow: 'رنک جهت نمایش',
  rankForShowInMarket: 'رنک جهت نمایش در مارکت',
  query: 'کوئری',
  image: 'تصویر',
  statusForShowInMarket: 'وضعیت (نمایش در مارکت)',
  submitCollectionInfoChanges: 'ثبت تغییرات اطلاعات مجموعه',
  metaDescription: 'Meta Description',
  metaKeywords: 'Meta Keywords',
  canonical: 'Canonical',
  robots: 'Robots',
  imageLink: 'لینک تصویر',
  submitSeoInfo: 'ثبت اطلاعات سئو',
  submitSeoInfoChanges: 'ثبت تغییرات اطلاعات سئو',
  createdTime: 'زمان ایجاد',
  requestsNum: 'تعداد درخواست‌ها',
  usersNum: 'تعداد کاربران',
  rate: 'امتیاز',
  earningAmount: 'میزان درآمد',
  packageType: 'نوع بسته',
  plan: 'پلن',
  stepPrice: 'قیمت پله‌ای',
  freePackage: 'پکیج رایگان',
  stepPackage: 'پکیج پله‌ای',
  payPerUsage: 'پرداخت به میزان استفاده',
  deleteLogDescriptionWithLogInfo: (apiName?: string, userName?: string) =>
    `با پاک کردن این مورد، بسته API «\u2066${apiName}\u2069» کاربر «\u2066${userName}\u2069» از بین خواهد رفت.`,
  deleteLogWithNumberDescription: (count: number) =>
    `شما ${count} مورد را انتخاب کرده‌اید، با پاک کردن این موارد تمامی بسته‌های API کاربران انتخاب شده از بین خواهد رفت.`,
  return: 'بازگشت',
  addNewQuestion: 'افزودن سوال جدید',
  createMessage: 'افزودن پیام...',
  questions: 'سوالات',
};

export default strings;
